Vagrant.configure("2") do |config|
  
  # Base Ubuntu box
  config.vm.box = "ubuntu/focal64"

  # Define a hostname for the VM
  config.vm.hostname = "web-server"

  # Configure network - make the server accessible to the client
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provisioning - Install NGINX
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    echo "<h1> Hello World </h1>" > /var/www/html/index.html
  SHELL

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Lower memory allocation to 1GB
    vb.cpus = 1         # Use 1 CPU core to reduce strain
    vb.gui = true  # Show the GUI so you can see the VM boot process
  end
end